config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users,
  path:'',
  path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
  controllers: {sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords', confirmations: 'users/confirmations'}

  get 'cart_items/member_cart'

  get 'headcounts/new_entrance'
  get 'headcounts/new_exit'
  get 'pages/my_counters'
  get 'pages/user_page'
  get 'pages/admin_page'
  post 'scanner/scan_result'

  # get 'basic-qr-code-reader', to: 'basic_qr_codes#index'
  get 'scanner/index'
  # get 'basic_qr_codes/index'

  get '/service-worker.js', to: 'service_workers/workers#index'
  get '/manifest.json', to: 'service_workers/manifests#index'
  get '/offline.html', to: 'service_workers/workers#offline'

  resources :headcounts do 
    member do 
      
    end
  end
end

app/models/headcount.rb
class Headcount < ApplicationRecord
    belongs_to :user
end

app/controllers/headcounts_controller.rb
class HeadcountsController < ApplicationController
  before_action :authenticate_user!, except: [:new_entrance, :new_exit]
  
  def index 
    user = current_user 
    @headcounts = user.headcounts 
  end
  
  def show 
    require 'rqrcode'
    user = current_user
    id = params[:id]
    headcount = Headcount.find(id)
    if headcount && headcount.user == user 
      @headcount = headcount 
      qr_code = headcount.qr_code
      entrance_code = headcount.entrance_code 
      exit_code = headcount.exit_code 

      #   Create qr code for each entry code
      qr_code = RQRCode::QRCode.new(headcount.qr_code)
      entrance_code = RQRCode::QRCode.new(headcount.entrance_code) 
      exit_code = RQRCode::QRCode.new(headcount.exit_code)

      qr_img = qr_code.as_png(
        bit_depth: 1,
        border_modules: 4,
        color_mode: ChunkyPNG::COLOR_GRAYSCALE,
        color: 'black',
        file: nil,
        fill: 'white',
        module_px_size: 6,
        resize_exactly_to: false,
        resize_gte_to: false,
        size: 320
      )
      entrance_img = entrance_code.as_png(
        bit_depth: 1,
        border_modules: 4,
        color_mode: ChunkyPNG::COLOR_GRAYSCALE,
        color: 'black',
        file: nil,
        fill: 'white',
        module_px_size: 6,
        resize_exactly_to: false,
        resize_gte_to: false,
        size: 320
      )
      exit_img = exit_code.as_png(
        bit_depth: 1,
        border_modules: 4,
        color_mode: ChunkyPNG::COLOR_GRAYSCALE,
        color: 'black',
        file: nil,
        fill: 'white',
        module_px_size: 6,
        resize_exactly_to: false,
        resize_gte_to: false,
        size: 320
      )

      @qr_img = qr_img.to_image.to_data_url
      @entrance_img = entrance_img.to_image.to_data_url 
      @exit_img = exit_img.to_image.to_data_url 

    end
  end

  def new 
    user = current_user 
    @headcount = user.headcounts.new
  end
  
  def create 
    user = current_user 
    headcount = user.headcounts.create(headcount_params)
    time_stamp = Time.now.to_f.to_i.to_s
    random_letters1 = (0...4).map { ('a'..'z').to_a[rand(26)] }.join
    random_letters2 = (0...4).map { ('a'..'z').to_a[rand(26)] }.join
    random_letters3 = (0...4).map { ('a'..'z').to_a[rand(26)] }.join
    random_letters4 = (0...4).map { ('a'..'z').to_a[rand(26)] }.join

    headcount.qr_code = 'telecounter' + time_stamp + random_letters1 + 'qr'
    headcount.entrance_code = 'telecounter' + time_stamp + random_letters2 + 'entrance'
    headcount.exit_code = 'telecounter' + time_stamp + random_letters3 + 'exit'
    headcount.stamp = 'telecounter' + time_stamp + random_letters4 + 'stamp'
    if headcount.save
      redirect_to pages_my_counters_path
    end

  end

  def update 

  end

  def delete 

  end

  def destroy 

  end

  def new_entrance
    stamp = params[:id]
    quant = params[:quant].to_i
    headcount = Headcount.find_by_stamp(stamp)
    current_count = headcount.current_count 
    current_count += quant
    headcount.current_count = current_count 
    headcount.save 
    @id = headcount.stamp
    @current_count = current_count
    AddNewEntranceJob.perform_later(@id, @current_count)
  end

  def new_exit
    stamp = params[:id]
    quant = params[:quant].to_i
    headcount = Headcount.find_by_stamp(stamp)
    current_count = headcount.current_count 
    if current_count > 0
      current_count -= quant 
      current_count = [current_count, 0].max
      headcount.current_count = current_count 
      headcount.save 
      @id = headcount.stamp
      @current_count = current_count
      AddNewEntranceJob.perform_later(@id, @current_count)
    end
  end

  private 

  def headcount_params
    params.require(:headcount).permit(:nickname, :max_count)
  end

end

app/helpers/headcounts_helper.rb
module HeadcountsHelper
end

app/views/headcounts/_current_count.html.erb
<%= content_tag :div, data: { controller: 'progress-bar' } do %>
  <%= tag :div, id: id, data: { target: 'progress-bar.progress_bar' } %>
<% end %>

app/views/headcounts/_progress_bar.html.erb
<%= content_tag :div, class: 'progress', data: { controller: 'progress-bar' } do %>
  <%= tag :div, class: 'progress-bar', id: id, data: { target: 'progress-bar.progress_bar' } %>
<% end %>

app/views/headcounts/index.html.erb
<div class='container mt-3 mb-4'>
    <% @headcounts.each do |headcount| %>
        <%= link_to headcount_path(headcount) do %>
        <div class='row'>
            <div class='col-md-6'>
                <p class='text-info'><%= headcount.nickname %></p>
            </div>
            <div class='col-md-6'>
                <p class='text-secondary'>Maximum Number Allowed: <%= headcount.max_count %></p>
            </div>
        </div>
        <% end %>
        <hr/>
    <% end %>
</div>

app/views/headcounts/new.html.erb
<div class='container mb-4 mt-4'>
  <%= form_for @headcount do |p| %>
      <ul class='list-group list-group-flush'>
          <li class='list-group-item'>
            <h4><%= p.label 'Assign a Nickname' %></h4>
            <%= p.text_field :nickname, class: 'form-control' %>
          </li>
          <li class='list-group-item'>
            <h4><%= p.label 'Set Maximum Number of Visitors Allowed' %></h4>
            <%= p.number_field :max_count, class: 'form-control' %>
          </li>
          
          <li class='list-group-item'>
              <%= p.submit 'Create', class:'btn btn-outline-success' %>
              <%= link_to 'Back Home', pages_my_counters_path, class:'btn btn-outline-info ml-4' %>
          </li>
      </ul>
  <% end %>
</div>

app/views/headcounts/new_exit.html.erb
<h1>Headcounts#new_exit</h1>
<p>Find me in app/views/headcounts/new_exit.html.erb</p>

app/views/headcounts/show.html.erb
    
<main role="main">
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <h2><%= @headcount.nickname %></h2>
            <h4 class='text-info mt-4'>
               Max Capacity: <%= @headcount.max_count %>
            </h4>
            <h4 data-controller='progress-bar'>
                Current Capacity: 
                <span id='<%= @headcount.stamp %>' data-target='progress-bar.progress_bar'>
                    <%= @headcount.current_count %>
                </span>
            </h4>
        </div>
    </div>
    <div class='container mb-2'>

    </div>
    <div class="container mb-5">
        <div class="accordion mb-4" id="accordionExample">
            <div class="card">
                <div class="card-header" id="headingOne">
                <h2 class="mb-0 text-center">
                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    QR Code For Entrance Control
                    </button>
                </h2>
                </div>

                <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                    <div class="card-body text-center">
                        <%= image_tag @entrance_img %>
                    </div>
                    <div class='card-footer text-center'>
                        <%= link_to 'Go To Entrance Control Page', pages_admin_page_path(:id => @headcount.id, :type => 'entrance'), class:'btn btn-outline-success' %>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header" id="headingTwo">
                <h2 class="mb-0 text-center">
                    <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    QR Code For Exit Control
                    </button>
                </h2>
                </div>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                    <div class="card-body text-center">
                        <%= image_tag @exit_img %>
                    </div>
                    <div class='card-footer text-center'>
                        <%= link_to 'Go To Exit Control Page', pages_admin_page_path(:id => @headcount.id, :type => 'exit'), class:'btn btn-outline-success' %>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header" id="headingThree">
                <h2 class="mb-0 text-center">
                    <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    QR Code for Control on Both Entrance and Exit
                    </button>
                </h2>
                </div>
                <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                    <div class="card-body text-center">
                        <%= image_tag @qr_img %>
                    </div>
                    <div class='card-footer text-center'>
                        <%= link_to 'Go To Control Both Entrance and Exit', pages_admin_page_path(:id => @headcount.id, :type => 'both'), class:'btn btn-outline-success' %>
                    </div>
                </div>
            </div>
        </div>

        <%= link_to 'Back', pages_my_counters_path, class:'btn btn-success btn-block' %>

    </div>
</main>