config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users,
  path:'',
  path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
  controllers: {sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords', confirmations: 'users/confirmations'}

  get 'cart_items/member_cart'

  get 'headcounts/new_entrance'
  get 'headcounts/new_exit'
  get 'pages/my_counters'
  get 'pages/user_page'
  get 'pages/admin_page'
  post 'scanner/scan_result'

  # get 'basic-qr-code-reader', to: 'basic_qr_codes#index'
  get 'scanner/index'
  # get 'basic_qr_codes/index'

  get '/service-worker.js', to: 'service_workers/workers#index'
  get '/manifest.json', to: 'service_workers/manifests#index'
  get '/offline.html', to: 'service_workers/workers#offline'

  resources :headcounts do 
    member do 
      
    end
  end
end

app/views/pages/admin_page.html.erb
<style>
    .greenCircle {
        border-radius: 50%;
        width: 120px;
        height: 120px;
        padding-top: 45px;
        background: #2ec97e;
        border: 2px solid #2ec97e;
        color: #fff;
        text-align: center;
        font: 25px Arial, sans-serif;
        display: block;
        margin-left: auto;
        margin-right: auto;
    }
    .greenCircle:hover {
        color: #fff;
        text-decoration: none;
    }

    .blueCircle {
        border-radius: 50%;
        width: 120px;
        height: 120px;
        padding-top: 45px;
        background: #1f80e0;
        border: 2px solid #1f80e0;
        color: #fff;
        text-align: center;
        font: 25px Arial, sans-serif;
        display: block;
        margin-left: auto;
        margin-right: auto;
    }
    .blueCircle:hover {
        color: #fff;
        text-decoration: none;
    }
</style>
<% if user_signed_in? %>
    <div class="card text-center mt-5">
        <div class="card-header">
            Current Capacity: 
            <span data-controller="progress-bar">
                <span id="<%= @headcount.stamp %>" data-target="progress-bar.progress_bar">
                    <%= @headcount.current_count %>
                </span>
            </span>
        </div>
        <div class="card-body">
            <% if @unlock_type == 'entrance' || @unlock_type == 'both' %>
                <p class="card-text">
                    <%= link_to '+ 1', headcounts_new_entrance_path(:id => @headcount.stamp, :quant => 1), id: 'new_entrance', class:'blueCircle', remote: true %>
                </p>
                <p class="card-text">
                    <%= link_to '+ 5', headcounts_new_entrance_path(:id => @headcount.stamp, :quant => 5), id: 'new_entrance', class:'blueCircle', remote: true %>
                </p>
                <p class="card-text">
                    <%= link_to '+ 10', headcounts_new_entrance_path(:id => @headcount.stamp, :quant => 10), id: 'new_entrance', class:'blueCircle', remote: true %>
                </p>
            <% end %>
            <% if @unlock_type == 'exit' || @unlock_type == 'both' %>
                <p class="card-text">
                    <%= link_to '- 1', headcounts_new_exit_path(:id => @headcount.stamp, :quant => 1), id: 'new_entrance', class: 'greenCircle', remote: true %>
                </p>
                <p class="card-text">
                    <%= link_to '- 5', headcounts_new_exit_path(:id => @headcount.stamp, :quant => 5), id: 'new_entrance', class: 'greenCircle', remote: true %>
                </p>
                <p class="card-text">
                    <%= link_to '- 10', headcounts_new_exit_path(:id => @headcount.stamp, :quant => 10), id: 'new_entrance', class: 'greenCircle', remote: true %>
                </p>
            <% end %>
        </div>
        <div class="card-footer text-muted">
            <%= link_to 'Back', headcount_path(@headcount), class:'btn btn-success' %>
        </div>
    </div>
<% end %>

app/views/pages/home.html.erb
<div class='container text-center' style='margin-top: 25vh;'>
    <% if user_signed_in? %>
        <div class='row mb-5'>
            <%= link_to 'Check/Create Counter', pages_my_counters_path, class:'btn btn-outline-success btn-block' %>
        </div>
    <% else %>
        <div class='row mb-5'>
            <%= link_to 'Sign In', new_user_session_path, class:'btn btn-outline-success btn-block' %>
        </div>
    <% end %>
    <div class='row'>
        <%= link_to 'Scan To Connect', scanner_index_path, class:'btn btn-outline-primary btn-block' %>
    </div>
</div>

app/views/pages/my_counters.html.erb
<div class='container mt-5'>
    <% if !@headcounts.blank? %>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>Counter Name</th>
                    <th>Maximum Capacity</th>
                    <th>Current Capacity</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <% @headcounts.each do |head| %>
                <tr>
                    <td><%= head.nickname %></td>
                    <td><%= head.max_count %></td>
                    <td>
                    <span data-controller='progress-bar'>
                        <span id='<%= head.stamp %>' data-target='progress-bar.progress_bar'>
                            <%= head.current_count %>
                        </span>
                    </span>
                    </td>
                    <td>
                    <%= link_to 'Check it out', headcount_path(head), class:'btn btn-sm btn-success'%>
                    </td>
                </tr>
                <% end %>
                </tbody>
            </table>
        </div>
    <% end %>
    <%= link_to 'Create New Counter', new_headcount_path, class:'btn btn-outline-info' %>
</div>

app/views/pages/user_page.html.erb
<style>
    .greenCircle {
        border-radius: 50%;
        width: 120px;
        height: 120px;
        padding-top: 45px;
        background: #2ec97e;
        border: 2px solid #2ec97e;
        color: #fff;
        text-align: center;
        font: 25px Arial, sans-serif;
        display: block;
        margin-left: auto;
        margin-right: auto;
    }
    .greenCircle:hover {
        color: #fff;
        text-decoration: none;
    }

    .blueCircle {
        border-radius: 50%;
        width: 120px;
        height: 120px;
        padding-top: 45px;
        background: #1f80e0;
        border: 2px solid #1f80e0;
        color: #fff;
        text-align: center;
        font: 25px Arial, sans-serif;
        display: block;
        margin-left: auto;
        margin-right: auto;
    }
    .blueCircle:hover {
        color: #fff;
        text-decoration: none;
    }
</style>

<% if session[:unlock_counter] %>
    <div class="card text-center">
    <div class="card-header">
        Current Capacity: 
        <span data-controller="progress-bar">
            <span id="<%= @headcount.stamp %>" data-target="progress-bar.progress_bar">
                <%= @headcount.current_count %>
            </span>
        </span>
    </div>
    <div class="card-body">
        <% if @unlock_type == 'entrance' || @unlock_type == 'both' %>
            <p class="card-text">
                <%= link_to '+ 1', headcounts_new_entrance_path(:id => @headcount.stamp, :quant => 1), id: 'new_entrance', class: 'blueCircle', remote: true %>
            </p>
            <p class="card-text">
                <%= link_to '+ 5', headcounts_new_entrance_path(:id => @headcount.stamp, :quant => 5), id: 'new_entrance', class:'blueCircle', remote: true %>
            </p>
            <p class="card-text">
                <%= link_to '+ 10', headcounts_new_entrance_path(:id => @headcount.stamp, :quant => 10), id: 'new_entrance', class:'blueCircle', remote: true %>
            </p>
        <% end %>
        <% if @unlock_type == 'exit' || @unlock_type == 'both' %>
            <p class="card-text">
                <%= link_to '- 1', headcounts_new_exit_path(:id => @headcount.stamp, :quant => 1), id: 'new_entrance', class: 'greenCircle', remote: true %>
            </p>
            <p class="card-text">
                <%= link_to '- 5', headcounts_new_exit_path(:id => @headcount.stamp, :quant => 5), id: 'new_entrance', class: 'greenCircle', remote: true %>
            </p>
            <p class="card-text">
                <%= link_to '- 10', headcounts_new_exit_path(:id => @headcount.stamp, :quant => 10), id: 'new_entrance', class: 'greenCircle', remote: true %>
            </p>
        <% end %>
    </div>
    <div class="card-footer text-muted">
    </div>
    </div>
<% end %>